### PR TITLE
Initialized with Login Page

### PR DESCRIPTION
**Pull request by iharshit009**
Completed Login Page
Build Navigation
@raj454raj  Please review this

### CODE REVIEW

**Review by aakashpothepalli — APPROVED** [review]

**Comment by raj454raj** [comment]
Hey @iharshit009, how will the login work?
Can you post some screenshots? Also, there is one more team who is working on creating an Android app. You can also collaborate with them. Let me know if you're interested over raj454raj@gmail.com

**Comment by aakashpothepalli** [comment]
Hey @raj454raj  , Is the app built using flutter ? If yes , then I am ready to collaborate :)

**Comment by raj454raj** [comment]
Hey @aakashpothepalli please share your telegram handle over email, will add you to the group.

**Comment by aakashpothepalli** [comment]
@raj454raj sent, please check :)

**Pull request closed without merging**
